## Получение истории торгов

Цель:
Практический кейс для понимания работы MOEX ISS

Источник:
https://moexapi.tech-order.ru/common_info_about_api

Входные условия:
Инструмент, рынок, режим торгов, период.

In [2]:
import requests
import pandas as pd

pd.set_option('display.max_columns', None)

In [3]:
#Получение информации о доступных торговых системах

engine_url = 'https://iss.moex.com/iss/engines.json'

engine_response = requests.get(
    url=engine_url,
    timeout=30
)
print(engine_response.status_code)

engines_data = engine_response.json()
engines_df = pd.DataFrame(
    data=engines_data["engines"]["data"],
    columns=engines_data["engines"]["columns"],
)

engines_df.head()

200

   id       name                             title
0   1      stock  Фондовый рынок и рынок депозитов
1   2      state            Рынок ГЦБ (размещение)
2   3   currency                    Валютный рынок
3   4    futures                     Срочный рынок
4   5  commodity                    Товарный рынок

In [4]:
#Получение информации о доступных рынках в системе "stock" - Фондовый рынок и рынок депозитов

markets_engines = 'stock'
markets_url = rf'https://iss.moex.com/iss/engines/{markets_engines}/markets.json'

markets_response = requests.get(
    url=markets_url,
    timeout=30
)
print(markets_response.status_code)

markets_data = markets_response.json()
markets_df = pd.DataFrame(
    data=markets_data['markets']['data'],
    columns=markets_data['markets']['columns']
)

markets_df.head(15)

200

    id           NAME                                   title
0    5          index                 Индексы фондового рынка
1    1         shares                             Рынок акций
2    2          bonds                         Рынок облигаций
3    4            ndm               Режим переговорных сделок
4   29            otc                                     ОТС
5   27            ccp                               РЕПО с ЦК
6   35        deposit                           Депозиты с ЦК
7    3           repo                       Рынок сделок РЕПО
8   28            qnv                         Квал. инвесторы
9   36           mamc  Мультивалютный рынок смешанных активов
10  47  foreignshares                        Иностранные ц.б.
11  49     foreignndm                    Иностранные ц.б. РПС
12  33      moexboard                              MOEX Board
13  46            gcc                         РЕПО с ЦК с КСУ
14  54         credit                          Рынок кредитов

In [5]:
#Получение информации о режиме торгов

board_engines = 'stock'
board_markets = 'shares'
board_url = rf'https://iss.moex.com/iss/engines/{board_engines}/markets/{board_markets}/board.json'

board_response = requests.get(
    url=board_url,
    timeout=30
)
print(board_url)
print(board_response.status_code)

board_data = board_response.json()
board_df = pd.DataFrame(
    data=board_data['boards']['data'],
    columns=board_data['boards']['columns']
)

board_df.head(15)

https://iss.moex.com/iss/engines/stock/markets/shares/board.json
200

,id,board_group_id,boardid,title,is_traded
0,1,6,EQBR,Основной режим: А1-Акции и паи - безадрес.,0
1,2,6,EQBS,Основной режим: А2-Акции и паи - безадрес.,0
2,95,30,EQCC,ЦК - режим основных торгов - безадрес.,0
3,117,6,EQDE,Основной режим: Акции Д - безадрес.,0
4,100,42,EQDP,Крупные пакеты - Акции - безадрес.,0
5,28,6,EQLI,Основной режим: И-Акции - безадрес.,0
6,3,6,EQLV,Основной режим: В-Акции и РДР - безадрес.,0
7,5,6,EQNE,Основной режим: Акции и паи внесписочные - без...,0
8,4,6,EQNL,Основной режим: Б-Акции и паи - безадрес.,0
9,260,99,EQTD,Т0: ETF (USD) - безадрес.,0
10,315,159,EQTU,Т0: ETF (EUR) - безадрес.,0
11,36,21,SMAL,Т+: Неполные лоты (акции) - безадрес.,1
12,281,125,SPEQ,Поставка по СК (акции),1
13,313,157,TQBE,Т+: Акции и ДР (EUR) - безадрес.,0
14,129,57,TQBR,Т+: Акции и ДР - безадрес.,1

In [11]:
#Список инструментов выбранного режима
securities_engines = 'stock'
securities_markets = 'index'
securities_board = 'SNDX'
securities_url = rf'https://iss.moex.com/iss/engines/{securities_engines}/markets/{securities_markets}/boards/{securities_board}/securities.json'

securities_params = {
    "iss.only": "securities",
}

securities_response = requests.get(
    url=securities_url,
    params=securities_params,
    timeout=30
)

print(securities_url)
print(securities_response.status_code)

securities_data = securities_response.json()
securities_df = pd.DataFrame(
    data=securities_data['securities']['data'],
    columns=securities_data['securities']['columns']
)

securities_df.head(5)

https://iss.moex.com/iss/engines/stock/markets/index/boards/SNDX/securities.json
200

,SECID,BOARDID,NAME,DECIMALS,SHORTNAME,ANNUALHIGH,ANNUALLOW,CURRENCYID,CALCMODE
0,IMOEX,SNDX,Индекс МосБиржи,2,Индекс МосБиржи,3014.21,1898.51,RUB,PR
1,IMOEX2,SNDX,IMOEX2 – значения индекса МосБиржи за весь тор...,2,Индекс МосБиржи (все сессии),3018.59,1896.43,RUB,PR
2,MECHTR,SNDX,Индекс МосБиржи химии и нефтехимии полной дохо...,4,MOEX Chemicals Total Return,78187.81,47537.00,RUB,TRB
3,MECHTRN,SNDX,Индекс МосБиржи химии и нефтехимии полной дохо...,4,MOEX Chemicals Net TR-NR,68963.73,41903.53,RUB,TRN
4,MECHTRR,SNDX,Индекс МосБиржи химии и нефтехимии полной дохо...,4,MOEX Chemicals Net TR-Res,70243.51,42684.63,RUB,TRN

In [12]:
#Дневная история IMOEX за период
history_engine = "stock"
history_market = "index"
history_board = "SNDX"
history_security = "IMOEX"

history_url = rf'https://iss.moex.com/iss/history/engines/{history_engine}/markets/{history_market}/boards/{history_board}/securities/{history_security}.json'
history_params = {
    "from": '2026-07-01',
    "till": '2026-07-15',
    "lang": 'ru',
}

history_response = requests.get(
    url=history_url,
    params=history_params,
    timeout=30
)

print(history_url)
print(history_response.status_code)

history_data = history_response.json()


history_df = pd.DataFrame(
    data=history_data["history"]["data"],
    columns=history_data["history"]["columns"],
)

history_df.head()

https://iss.moex.com/iss/history/engines/stock/markets/index/boards/SNDX/securities/IMOEX.json
200

,BOARDID,SECID,TRADEDATE,SHORTNAME,NAME,CLOSE,OPEN,HIGH,LOW,VALUE,DURATION,YIELD,DECIMALS,CAPITALIZATION,CURRENCYID,DIVISOR,TRADINGSESSION,VOLUME,TRADE_SESSION_DATE,RECALC_DATE
0,SNDX,IMOEX,2026-07-01,Индекс МосБиржи,Индекс МосБиржи,2344.55,2360.90,2374.74,2333.65,5.050346e+10,0,0,2,6.044757e+12,RUB,2.578216e+09,3,None,2026-07-01,None
1,SNDX,IMOEX,2026-07-02,Индекс МосБиржи,Индекс МосБиржи,2256.06,2334.26,2335.45,2244.36,6.571257e+10,0,0,2,5.816608e+12,RUB,2.578216e+09,3,None,2026-07-02,None
2,SNDX,IMOEX,2026-07-03,Индекс МосБиржи,Индекс МосБиржи,2242.84,2259.22,2266.14,2210.24,6.580172e+10,0,0,2,5.782529e+12,RUB,2.578216e+09,3,None,2026-07-03,None
3,SNDX,IMOEX,2026-07-06,Индекс МосБиржи,Индекс МосБиржи,2194.14,2241.37,2259.92,2164.81,1.151530e+11,0,0,2,5.656980e+12,RUB,2.578216e+09,3,None,2026-07-06,None
4,SNDX,IMOEX,2026-07-07,Индекс МосБиржи,Индекс МосБиржи,2190.39,2168.29,2198.87,2117.50,1.149408e+11,0,0,2,5.647288e+12,RUB,2.578216e+09,3,None,2026-07-07,None

In [13]:
#Получить свечи указанного инструмента по выбранному режиму торгов IMOEX - 1час
candles_engine = "stock"
candles_market = "index"
candles_board = "SNDX"
candles_security = "IMOEX"

candles_url = rf'https://iss.moex.com/iss/engines/{candles_engine}/markets/{candles_market}/boards/{candles_board}/securities/{candles_security}/candles.json'
candles_params = {
    "from": '2026-07-01',
    "till": '2026-07-03',
    'interval': 60,
}

candles_response = requests.get(
    url=candles_url,
    params=candles_params,
    timeout=30
)

print(candles_response.url)
print(candles_response.status_code)

candles_data = candles_response.json()
candles_df = pd.DataFrame(
    data=candles_data["candles"]["data"],
    columns=candles_data["candles"]["columns"],
)

candles_df.head()

https://iss.moex.com/iss/engines/stock/markets/index/boards/SNDX/securities/IMOEX/candles.json?from=2026-07-01&till=2026-07-03&interval=60
200

,open,close,high,low,value,volume,begin,end
0,2360.90,2362.90,2364.14,2356.28,7.353409e+08,0,2026-07-01 09:00:00,2026-07-01 09:59:59
1,2362.92,2341.69,2369.31,2341.18,6.718856e+09,0,2026-07-01 10:00:00,2026-07-01 10:59:59
2,2341.77,2344.32,2349.57,2333.65,7.028784e+09,0,2026-07-01 11:00:00,2026-07-01 11:59:59
3,2344.32,2365.11,2374.74,2338.36,9.291431e+09,0,2026-07-01 12:00:00,2026-07-01 12:59:59
4,2365.10,2360.00,2367.64,2356.91,3.800926e+09,0,2026-07-01 13:00:00,2026-07-01 13:59:59

In [14]:
#Получить свечи указанного инструмента по выбранному режиму торгов SBER - 1час
candles_sber_engine = "stock"
candles_sber_market = "shares"
candles_sber_board = "TQBR"
candles_sber_security = "sber"

candles_sber_url = rf'https://iss.moex.com/iss/engines/{candles_sber_engine}/markets/{candles_sber_market}/boards/{candles_sber_board}/securities/{candles_sber_security}/candles.json'
candles_sber_params = {
    "from": '2026-07-01',
    "till": '2026-07-03',
    'interval': 60,
}

candles_sber_response = requests.get(
    url=candles_sber_url,
    params=candles_sber_params,
    timeout=30
)

print(candles_sber_response.url)
print(candles_sber_response.status_code)

candles_sber_data = candles_sber_response.json()
candles_sber_df = pd.DataFrame(
    data=candles_sber_data["candles"]["data"],
    columns=candles_sber_data["candles"]["columns"],
)

candles_sber_df.head(15)

https://iss.moex.com/iss/engines/stock/markets/shares/boards/TQBR/securities/sber/candles.json?from=2026-07-01&till=2026-07-03&interval=60
200

,open,close,high,low,value,volume,begin,end
0,308.12,308.12,308.12,308.12,1.431834e+06,4647,2026-07-01 06:00:00,2026-07-01 06:59:59
1,308.12,308.41,308.73,307.74,1.858488e+08,602984,2026-07-01 07:00:00,2026-07-01 07:59:59
2,308.42,309.29,309.90,308.30,3.885508e+08,1257532,2026-07-01 08:00:00,2026-07-01 08:59:59
3,309.14,310.23,310.50,308.81,7.061487e+08,2280787,2026-07-01 09:00:00,2026-07-01 09:59:59
4,310.22,308.68,310.83,308.65,8.942057e+08,2887715,2026-07-01 10:00:00,2026-07-01 10:59:59
5,308.68,308.42,308.79,307.00,1.123534e+09,3650231,2026-07-01 11:00:00,2026-07-01 11:59:59
6,308.42,310.54,311.57,307.50,1.663440e+09,5362750,2026-07-01 12:00:00,2026-07-01 12:59:59
7,310.54,309.66,310.70,309.49,5.499470e+08,1774155,2026-07-01 13:00:00,2026-07-01 13:59:59
8,309.68,309.76,310.16,308.40,4.755372e+08,1537030,2026-07-01 14:00:00,2026-07-01 14:59:59
9,309.74,307.91,310.14,307.78,2.103610e+09,6805070,2026-07-01 15:00:00,2026-07-01 15:59:59
10,307.91,306.42,308.96,306.40,1.934170e+09,6289041,2026-07-01 16:00:00,2026-07-01 16:59:59
11,306.41,306.54,307.07,305.55,1.106789e+09,3615312,2026-07-01 17:00:00,2026-07-01 17:59:59
12,306.54,306.68,306.68,305.68,6.233794e+08,2037388,2026-07-01 18:00:00,2026-07-01 18:59:59
13,306.66,306.76,306.97,306.13,2.499374e+08,815024,2026-07-01 19:00:00,2026-07-01 19:59:59
14,306.76,306.65,306.96,306.54,2.111739e+08,688303,2026-07-01 20:00:00,2026-07-01 20:59:59

In [15]:
#Дневная история SBER за период
history_sber_engine = "stock"
history_sber_market = "shares"
history_sber_board = "TQBR"
history_sber_security = "sber"

history_sber_url = rf'https://iss.moex.com/iss/history/engines/{history_sber_engine}/markets/{history_sber_market}/boards/{history_sber_board}/securities/{history_sber_security}.json'
history_sber_params = {
    "from": '2026-07-01',
    "till": '2026-07-15',
    "lang": 'ru',
}

history_sber_response = requests.get(
    url=history_sber_url,
    params=history_sber_params,
    timeout=30
)

print(history_sber_url)
print(history_sber_response.status_code)

history_sber_data = history_sber_response.json()


history_sber_df = pd.DataFrame(
    data=history_sber_data["history"]["data"],
    columns=history_sber_data["history"]["columns"],
)

history_sber_df.head(20)

https://iss.moex.com/iss/history/engines/stock/markets/shares/boards/TQBR/securities/sber.json
200

,BOARDID,TRADEDATE,SHORTNAME,SECID,NUMTRADES,VALUE,OPEN,LOW,HIGH,LEGALCLOSEPRICE,WAPRICE,CLOSE,VOLUME,MARKETPRICE2,MARKETPRICE3,ADMITTEDQUOTE,MP2VALTRD,MARKETPRICE3TRADESVALUE,ADMITTEDVALUE,WAVAL,TRADINGSESSION,CURRENCYID,TRENDCLSPR,TRADE_SESSION_DATE
0,TQBR,2026-07-01,Сбербанк,SBER,181706,1.257712e+10,308.12,305.55,311.57,306.68,308.41,307.04,40780087,308.48,308.48,None,1.066855e+10,1.066855e+10,None,0,3,SUR,-0.34,2026-07-01
1,TQBR,2026-07-02,Сбербанк,SBER,197020,1.393199e+10,307.10,299.83,308.20,301.80,303.31,301.05,45930395,303.30,303.30,None,1.229356e+10,1.229356e+10,None,0,3,SUR,-1.95,2026-07-02
2,TQBR,2026-07-03,Сбербанк,SBER,161463,9.917346e+09,301.65,298.04,303.25,301.75,300.92,301.19,33006616,300.32,300.32,None,8.649960e+09,8.649960e+09,None,0,3,SUR,0.05,2026-07-03
3,TQBR,2026-07-06,Сбербанк,SBER,323901,1.508306e+10,301.39,294.07,305.60,298.68,300.40,298.77,50214521,300.12,300.12,None,1.187651e+10,1.187651e+10,None,0,3,SUR,-0.80,2026-07-06
4,TQBR,2026-07-07,Сбербанк,SBER,248284,1.459397e+10,299.02,292.12,299.47,296.93,295.40,298.98,49403734,295.01,295.01,None,1.250731e+10,1.250731e+10,None,0,3,SUR,0.07,2026-07-07
5,TQBR,2026-07-08,Сбербанк,SBER,262007,1.246919e+10,299.38,293.80,301.18,298.49,296.71,298.66,41979587,296.66,296.66,None,1.027894e+10,1.027894e+10,None,0,3,SUR,-0.11,2026-07-08
6,TQBR,2026-07-09,Сбербанк,SBER,187632,9.576906e+09,298.66,293.85,299.06,295.00,296.48,294.54,32299129,296.72,296.72,None,7.685572e+09,7.685572e+09,None,0,3,SUR,-1.38,2026-07-09
7,TQBR,2026-07-10,Сбербанк,SBER,206435,1.135411e+10,294.84,290.01,295.72,291.03,292.39,290.85,38827604,292.39,292.39,None,9.651643e+09,9.651643e+09,None,0,3,SUR,-1.25,2026-07-10
8,TQBR,2026-07-13,Сбербанк,SBER,256857,1.264531e+10,291.10,290.00,296.76,293.30,294.46,293.96,42948387,294.98,294.98,None,8.865174e+09,8.865174e+09,None,0,3,SUR,1.07,2026-07-13
9,TQBR,2026-07-14,Сбербанк,SBER,140598,1.064376e+10,294.50,293.45,296.10,294.79,294.92,294.56,36089498,294.97,294.97,None,9.559113e+09,9.559113e+09,None,0,3,SUR,0.20,2026-07-14
10,TQBR,2026-07-15,Сбербанк,SBER,228316,1.333076e+10,294.56,287.02,294.80,287.90,290.13,288.08,45945760,289.98,289.98,None,1.093254e+10,1.093254e+10,None,0,3,SUR,-2.20,2026-07-15

In [16]:
# Для выгрузки данных, если в первую партию выгрузилось не все.

cursor = dict(
    zip(
        history_sber_data['history.cursor']["columns"],
        history_sber_data['history.cursor']["data"][0],
    )
)

history_sber_params["start"] = cursor['PAGESIZE']

history_sber_response = requests.get(
    url=history_sber_url,
    params=history_sber_params,
    timeout=30,
)

history_sber_response.raise_for_status()

print(history_sber_response.url)

history_sber_data = history_sber_response.json()

history_sber_page_2_df = pd.DataFrame(
    data=history_sber_data["history"]["data"],
    columns=history_sber_data["history"]["columns"],
)

history_sber_page_2_df.head()

https://iss.moex.com/iss/history/engines/stock/markets/shares/boards/TQBR/securities/sber.json?from=2026-07-01&till=2026-07-15&lang=ru&start=100

Empty DataFrame
Columns: [BOARDID, TRADEDATE, SHORTNAME, SECID, NUMTRADES, VALUE, OPEN, LOW, HIGH, LEGALCLOSEPRICE, WAPRICE, CLOSE, VOLUME, MARKETPRICE2, MARKETPRICE3, ADMITTEDQUOTE, MP2VALTRD, MARKETPRICE3TRADESVALUE, ADMITTEDVALUE, WAVAL, TRADINGSESSION, CURRENCYID, TRENDCLSPR, TRADE_SESSION_DATE]
Index: []

## Итоги исследования

Изучено:

- структура MOEX ISS: engine → market → board → security;
- получение списка инструментов;
- получение дневной истории;
- получение часовых свечей;
- структура ответа columns + data;
- служебный блок cursor;
- назначение параметров from, till, interval и start.

Пагинацию необходимо реализовать позднее в загрузчике больших объёмов данных.